
mybatis-plus:
  #MyBatis Mapper 所对应的 XML 文件位置
  mapper-locations: classpath*:mapper/*.xml
    #  MyBaits 别名包扫描路径，通过该属性可以给包中的类注册别名，
    #注册后在 Mapper 对应的 XML 文件中可以直接使用类名，而不用使用全限定的类名（即 XML 中调用的时候不用包含包名）
  typeAliasesPackage: com.yjt.study.projectentry.entry

spring:
  datasource:
    name: db
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 1412yjt
    driver-class-name: com.mysql.cj.jdbc.Driver
    filters:
    - stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20

server:
  port: 9090
  tomcat:
    uri-encoding: UTF-8
  servlet:
    context-path: /study
mybatis:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.yjt.study.projectentry.entry